select
    snapshot_id,
    hospital_id,
    reported_hospital_name as raw_reported_hospital_name,
    {{ hpt_clean_text('reported_hospital_name') }} as clean_reported_hospital_name,
    source_url,
    source_file_name,
    {{ hpt_clean_text('source_format') }} as source_format,
    file_hash,
    ingested_at as raw_ingested_at,
    {{ hpt_safe_timestamp('ingested_at') }} as ingested_at,
    published_last_updated_on as raw_published_last_updated_on,
    {{ hpt_safe_date('published_last_updated_on') }} as published_last_updated_on,
    schema_version,
    valid_from as raw_valid_from,
    {{ hpt_safe_timestamp('valid_from') }} as valid_from,
    attestation,
    confirm_attestation,
    attester_name,
    affirmation,
    confirm_affirmation,
    reported_state,
    license_number
from {{ source('bronze', 'hospital_mrf_snapshots') }}
